{
 "title": "Sun Grid Engine",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(free_memory_bytes,hostname)"
   },
   {
    "name": "Owner",
    "query": "label_values(job_priority_value{hostname=~\"$hostname\"},owner)"
   }
  ]
 },
 "panels": [
  { "title": "Job Priority", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job Priority Values: $hostname, $Owner",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job_priority_value{hostname=~\"$hostname\", owner=~\"$Owner\"}"
    }
   ]
  },
  { "title": "Job Status Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Jobs Running on $hostname",
   "type": "singlestat",
   "description": "Jobs currently running on host",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "repeat": "hostname",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(job_state_value{hostname=~\"$hostname\", owner=~\"$Owner\"} == 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Jobs Not running on $hostname",
   "type": "singlestat",
   "description": "Jobs currently not running on host",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(job_state_value{hostname=~\"$hostname\", owner=~\"$Owner\"} == 0)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Utilization for host $hostname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sge_cpu_utilization_percent{hostname=~\"$hostname\"}",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  { "title": "Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory Utilization By Host $hostname",
   "type": "graph",
   "description": "Provides memory utilization details for the specified host",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "repeat": "hostname",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "free_memory_bytes{hostname=~\"$hostname\"} / (1000 * 1000 * 1000)",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "sge_total_memory_bytes{hostname=~\"$hostname\"} / (1000 * 1000 * 1000)",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sge_used_memory_bytes{hostname=~\"$hostname\"} / (1000 * 1000 * 1000)",
     "legendFormat": "Used Memory"
    }
   ]
  }
 ]
}