test: false
port: 9081
pidfile: "/var/run/gridengine_prometheus.pid"
tls_config: ""
sge:
  arch: "lx-amd64"
  cell: "default"
  execd_port: 6445
  qmaster_port: 6444
  root: "/opt/sge"
  cluster_name: "p6444"
